version: "3"
services:
  app:
    container_name: thatblog
    restart: always
    build: ./
    ports:
      - "9080:80"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
